title:             BSides San Diego
email:             "bsdidessd@bsidessd.org"
description:       " "
author:            BsidesSD
baseurl:           "/BsidesSD"
url:               "https://k2sinfosec.github.io"
permalink:         pretty

# Social Profiles
twitter_username:  BsidesSD
github_username:   
facebook_username: 

#RSS
feed:
  path: feed.xml

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-twitter-plugin
